name: my_dog
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # for design
  cupertino_icons: ^1.0.2

  # connect network
  http: ^0.13.4
  http_interceptor: ^1.0.2
  dio: ^4.0.6
  connectivity_plus: ^2.3.6


  # database
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.0
  image_gallery_saver: ^1.7.1

  #share
  share_plus: ^4.0.10

  #permission
  permission_handler: ^10.0.0



  # image
  cached_network_image: ^3.2.1
  transparent_image: ^2.0.0
  image_picker: ^0.8.5+3

  # decoration
  flutter_staggered_grid_view: ^0.6.2
  lottie: ^1.3.0
  flutter_wallpaper_manager: ^0.0.3
  url_strategy: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
